### ISSUE TITLE
Health Bar Not appearing

### ISSUE THREAD

**Issue by tomtomy8** [tomtomy8/Pixel-Crime#1]
There is a null refrence exception in Unity whilst I am attempting to make the health bar text appear. This may be linked to the fact that the health bar is not changing size due to the health of the brawler.

**Comment by UmairEm** [comment]
where is code for health-bar in your repository?

**Comment by tomtomy8** [comment]
In Asset/Scripts/Battle.js

**Comment by tomtomy8** [comment]
After looking back through the scene after a 30 min break or so its now fixed
